language: php
matrix:
  include:
    - php: '5.4'
      env: SNIFF=1
    - php: '5.6'
      env: SNIFF=1
    - php: '7.0'
      env: SNIFF=1
    - php: 5.2
      dist: precise
      env: SNIFF=1
    - php: 5.3
      dist: precise
      env: SNIFF=1
before_script:
    - export PHPCS_DIR=/tmp/phpcs
    - export SNIFFS_DIR=/tmp/sniffs
    - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR; fi
    - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR; fi
    - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility; fi
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/phpcs --config-set installed_paths $SNIFFS_DIR; fi
    - if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
    - if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
    - if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi
    - if [[ "$SNIFF" == "1" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc; fi
script:
    - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - if [[ "$SNIFF" == "1" ]]; then jshint .; fi
    - if [[ "$SNIFF" == "1" ]]; then jscs .; fi
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php; fi
notifications:
    email: false
