language: php
matrix:
  include:
    - php: '7.2'
      env: PHPC_WPC=1
    - php: '7.1'
      env: PHPC_WPC=1
    - php: '7.0'
      env: PHPC_WPC=1
    - php: '5.6'
      env: PHPC_WPC=1
    - php: '5.5'
      env: PHPC_WPC=1
    - php: '5.4'
      env: PHPC_WPC=1
before_script:
    - pear install pear/PHP_CodeSniffer
    - export SNIFFS_DIR=/tmp/sniffs
    - |
      if [[ "$PHPC_WPC" == "1" ]]; then
        git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
        phpenv rehash
      fi
script:
    - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - |
      if [[ "$PHPC_WPC" == "1" ]]; then
        phpcs --config-set installed_paths $SNIFFS_DIR
        phpcs -p -s -v -n . --standard=WordPress-Core --extensions=php
      fi
notifications:
    email: false
